/**
 * Renders the whole zone -> fielder map as a markdown table and snapshots it
 * to playbook.md.
 *
 * Two jobs in one. It is the document to put in front of a coach — the tables
 * are readable without running anything. And because it is a snapshot, any
 * change to the map shows up as a diff in plain English rather than as a silent
 * shift in behaviour.
 *
 * Run `npx vitest -u` to accept an intended change.
 */

import { expect, it } from 'vitest';
import { FIELD_CONFIGS, fenceRadius, type Level, type Point } from '../field/geometry';
import {
  INFIELD_SECTORS,
  OUTFIELD_SECTORS,
  classify,
  type DepthBand,
} from '../field/zones';
import { primaryFor } from '../field/primary';
import { isPlausible } from '../field/play';

const RAD = Math.PI / 180;

const INFIELD_BAND_MIDS: Record<string, number> = { bunt: 35, in: 72.5, infield: 122.5 };
const OUTFIELD_BAND_FRACTIONS: Record<string, number> = {
  shallow: 0.15, medium: 0.475, deep: 0.775, wall: 0.95,
};

/** A representative point in the middle of a given band and sector. */
function sample(level: Level, band: DepthBand, from: number, to: number): Point {
  const cfg = FIELD_CONFIGS[level];
  const u = cfg.baseDistance / 90;
  const theta = ((from + to) / 2) * RAD;

  const r =
    band in INFIELD_BAND_MIDS
      ? INFIELD_BAND_MIDS[band] * u
      : (() => {
          const start = 150 * u;
          return start + OUTFIELD_BAND_FRACTIONS[band] * (fenceRadius(cfg, theta) - start);
        })();

  return { x: r * Math.sin(theta), y: r * Math.cos(theta) };
}

function table(level: Level, bands: DepthBand[], sectors: typeof INFIELD_SECTORS | typeof OUTFIELD_SECTORS) {
  const lines = [
    `| Sector | ${bands.map((b) => `${b} (ground)`).join(' | ')} | ${bands.map((b) => `${b} (air)`).join(' | ')} |`,
    `|${' --- |'.repeat(bands.length * 2 + 1)}`,
  ];

  for (const s of sectors) {
    const cells: string[] = [];
    for (const ball of ['ground', 'fly'] as const) {
      for (const band of bands) {
        const at = sample(level, band, s.from, s.to);
        const zone = classify(at, level);
        // A fly ball cannot land in the bunt band; printing an owner for it
        // would put a rule in front of a coach that never fires.
        if (!isPlausible(ball, zone)) {
          cells.push('—');
          continue;
        }
        // If the sample does not land in the band we aimed at, the band edges
        // and this table have drifted apart — say so rather than hide it.
        const drift = zone.band !== band ? '!' : '';
        cells.push(`${primaryFor(zone, ball, level).position}${drift}`);
      }
    }
    lines.push(`| \`${s.id}\` | ${cells.join(' | ')} |`);
  }

  return lines.join('\n');
}

it('playbook matches the snapshot', async () => {
  const doc: string[] = [
    '# Playbook',
    '',
    '_Generated by `src/engine/playbook.test.ts`. Do not edit by hand —',
    'change the tables in `src/field/primary.ts` and run `npx vitest -u`._',
    '',
    'Who the ball belongs to, by depth band and sector. A `!` means the sample',
    'point did not land in the band it was aimed at, which would mean the band',
    'edges have drifted.',
    '',
  ];

  for (const level of ['youth', 'adult'] as Level[]) {
    const cfg = FIELD_CONFIGS[level];
    doc.push(
      `## ${level === 'youth' ? 'Youth' : 'Adult'}`,
      '',
      `${cfg.baseDistance}' bases, ${cfg.moundDistance}' mound, fences ${cfg.fence.line}/${cfg.fence.center}/${cfg.fence.line}.`,
      '',
      '### Infield',
      '',
      table(level, ['bunt', 'in', 'infield'], INFIELD_SECTORS),
      '',
      '### Outfield',
      '',
      table(level, ['shallow', 'medium', 'deep', 'wall'], OUTFIELD_SECTORS),
      '',
    );
  }

  await expect(doc.join('\n')).toMatchFileSnapshot('../../playbook.md');
});
