/**
 * Builds the review packet — the document to put in front of somebody who
 * actually coaches.
 *
 * Everything here is generated by running the engine, so it cannot drift from
 * what the app does. The prose sections are the editorial layer: they say which
 * claims are contestable and where to point if you disagree.
 *
 * The output is snapshotted, so changing a convention shows up as a diff in
 * plain English rather than as a silent shift in behaviour.
 */

import { FIELD_CONFIGS, fenceRadius, type Level, type Point } from '../field/geometry';
import {
  INFIELD_SECTORS,
  OUTFIELD_SECTORS,
  classify,
  type DepthBand,
} from '../field/zones';
import { primaryFor } from '../field/primary';
import { buildPickoff, PICKOFFS, type PickoffId } from './pickoff';
import {
  buildFirstAndThird,
  CALL_NAMES,
  FIRST_THIRD_CALLS,
} from './firstAndThird';
import {
  DEFAULT_SITUATION,
  isPlausible,
  type BallType,
  type Outcome,
  type Outs,
  type Runners,
  type Situation,
} from '../field/play';
import type { Position, Posture } from '../field/alignments';
import { roleKey, type Assignment } from '../field/assignment';
import { resolvePlay } from './resolve';
import { BACKUP_ORDER } from './context';

const RAD = Math.PI / 180;

// --- sampling helpers ----------------------------------------------------

const INFIELD_BAND_MIDS: Record<string, number> = { bunt: 35, in: 72.5, infield: 122.5 };
const OUTFIELD_BAND_FRACTIONS: Record<string, number> = {
  shallow: 0.15, medium: 0.475, deep: 0.775, wall: 0.95,
};

/** A representative point in the middle of a given band and sector. */
function sample(level: Level, band: DepthBand, from: number, to: number): Point {
  const cfg = FIELD_CONFIGS[level];
  const u = cfg.baseDistance / 90;
  const theta = ((from + to) / 2) * RAD;

  const r =
    band in INFIELD_BAND_MIDS
      ? INFIELD_BAND_MIDS[band] * u
      : (() => {
          const start = 150 * u;
          return start + OUTFIELD_BAND_FRACTIONS[band] * (fenceRadius(cfg, theta) - start);
        })();

  return { x: r * Math.sin(theta), y: r * Math.cos(theta) };
}

const RUNNER_STATES: { label: string; runners: Runners }[] = [
  { label: 'empty', runners: { first: false, second: false, third: false } },
  { label: '1st', runners: { first: true, second: false, third: false } },
  { label: '2nd', runners: { first: false, second: true, third: false } },
  { label: '3rd', runners: { first: false, second: false, third: true } },
  { label: '1st + 2nd', runners: { first: true, second: true, third: false } },
  { label: '1st + 3rd', runners: { first: true, second: false, third: true } },
  { label: '2nd + 3rd', runners: { first: false, second: true, third: true } },
  { label: 'loaded', runners: { first: true, second: true, third: true } },
];

const BASE_LABEL: Record<string, string> = {
  first: '1st', second: '2nd', third: '3rd', home: 'home',
};

type Spot = { level?: Level; ball: BallType; at: Point; outcome: Outcome };

function run(spot: Spot, over: Partial<Situation> = {}) {
  const situation: Situation = { ...DEFAULT_SITUATION, level: spot.level ?? 'youth', ...over };
  return resolvePlay({ situation, ball: spot.ball, at: spot.at, outcome: spot.outcome });
}

/** "2nd → 1st", or "—" when nobody throws anywhere. */
function throwLine(spot: Spot, over: Partial<Situation>): string {
  const play = run(spot, over);
  if (play.throws.length === 0) return '—';
  return play.throws.map((t) => `${t.from} → ${BASE_LABEL[t.to]}`).join(', ');
}

/** Whoever holds a given role on this play. */
function whoHas(spot: Spot, over: Partial<Situation>, key: string): string {
  const play = run(spot, over);
  const hit = play.assignments.find((a) => roleKey(a.role) === key);
  return hit ? hit.position : '—';
}

const ROLE_PROSE: Record<string, string> = {
  'cover:second': 'stays on second',
  'relay:third': 'is the relay',
  'relay:home': 'is the relay',
  watch: 'has no job',
};

/**
 * What a given fielder is doing, in words. Reporting only his initials hides
 * the difference between covering a bag and trailing a relay, which is exactly
 * the distinction some of these rows exist to show.
 */
function whatDoes(spot: Spot, over: Partial<Situation>, pos: Position): string {
  const play = run(spot, over);
  const hit = play.assignments.find((a) => a.position === pos);
  if (!hit) return '—';
  const key = roleKey(hit.role);
  return `${pos} — ${ROLE_PROSE[key] ?? (key.startsWith('trail:') ? 'trails the relay' : key)}`;
}

// --- sections ------------------------------------------------------------

function ownershipTable(level: Level, bands: DepthBand[], sectors: typeof INFIELD_SECTORS | typeof OUTFIELD_SECTORS) {
  const lines = [
    `| Sector | ${bands.map((b) => `${b} (ground)`).join(' | ')} | ${bands.map((b) => `${b} (air)`).join(' | ')} |`,
    `|${' --- |'.repeat(bands.length * 2 + 1)}`,
  ];

  for (const s of sectors) {
    const cells: string[] = [];
    for (const ball of ['ground', 'fly'] as const) {
      for (const band of bands) {
        const at = sample(level, band, s.from, s.to);
        const zone = classify(at, level);
        // A fly ball cannot land in the bunt band; printing an owner for it
        // would put a rule in front of a coach that never fires.
        if (!isPlausible(ball, zone)) {
          cells.push('—');
          continue;
        }
        // If the sample does not land in the band we aimed at, the band edges
        // and this table have drifted apart — say so rather than hide it.
        const drift = zone.band !== band ? '!' : '';
        cells.push(`${primaryFor(zone, ball, level).position}${drift}`);
      }
    }
    lines.push(`| \`${s.id}\` | ${cells.join(' | ')} |`);
  }

  return lines.join('\n');
}

/** Where the throw goes, across every base state and out count. */
function throwTable(spot: Spot, postures: { label: string; posture: Posture }[]) {
  const lines = [
    `| Runners | Outs | ${postures.map((p) => p.label).join(' | ')} |`,
    `|${' --- |'.repeat(postures.length + 2)}`,
  ];

  for (const state of RUNNER_STATES) {
    for (const outs of [0, 1, 2] as Outs[]) {
      const cells = postures.map((p) =>
        throwLine(spot, { runners: state.runners, outs, posture: p.posture }),
      );
      lines.push(`| ${state.label} | ${outs} | ${cells.join(' | ')} |`);
    }
  }

  return lines.join('\n');
}

const HIT_TO = (level: Level, deg: number, ratio = 0.72): Spot => {
  const cfg = FIELD_CONFIGS[level];
  const theta = deg * RAD;
  const r = fenceRadius(cfg, theta) * ratio;
  return { level, ball: 'fly', at: { x: r * Math.sin(theta), y: r * Math.cos(theta) }, outcome: 'drops' };
};

const WALL_AT = (level: Level, deg: number): Spot => {
  const cfg = FIELD_CONFIGS[level];
  const theta = deg * RAD;
  const start = 150 * (cfg.baseDistance / 90);
  const r = start + 0.95 * (fenceRadius(cfg, theta) - start);
  return { level, ball: 'fly', at: { x: r * Math.sin(theta), y: r * Math.cos(theta) }, outcome: 'toWall' };
};

function cutTable() {
  const manOnSecond: Partial<Situation> = {
    runners: { first: false, second: true, third: false }, outs: 1,
  };
  const manOnFirst: Partial<Situation> = {
    runners: { first: true, second: false, third: false }, outs: 0,
  };

  const rows: [string, string, string][] = [
    [
      'Throw home from left field',
      whoHas(HIT_TO('youth', -31), manOnSecond, 'cutoff:home'),
      whoHas(HIT_TO('adult', -31), manOnSecond, 'cutoff:home'),
    ],
    [
      'Throw home from centre field',
      whoHas(HIT_TO('youth', 0), manOnSecond, 'cutoff:home'),
      whoHas(HIT_TO('adult', 0), manOnSecond, 'cutoff:home'),
    ],
    [
      'Throw home from right field',
      whoHas(HIT_TO('youth', 31), manOnSecond, 'cutoff:home'),
      whoHas(HIT_TO('adult', 31), manOnSecond, 'cutoff:home'),
    ],
    [
      'Throw to third from left field',
      whoHas(HIT_TO('youth', -31), manOnFirst, 'cutoff:third'),
      whoHas(HIT_TO('adult', -31), manOnFirst, 'cutoff:third'),
    ],
    [
      'Relay man, ball to the wall in left-centre',
      whoHas(WALL_AT('youth', -17), {}, 'relay:third'),
      whoHas(WALL_AT('adult', -17), {}, 'relay:third'),
    ],
    [
      'The other middle infielder, ball to the wall',
      whatDoes(WALL_AT('youth', -17), {}, '2B'),
      whatDoes(WALL_AT('adult', -17), {}, '2B'),
    ],
  ];

  return [
    '| Situation | Youth | Adult |',
    '| --- | --- | --- |',
    ...rows.map(([what, y, a]) => `| ${what} | ${y} | ${a} |`),
  ].join('\n');
}

function coverFirstTable() {
  const groundToShort: Spot = { ball: 'ground', at: { x: -27, y: 87 }, outcome: 'fielded' };
  const groundToFirst: Spot = { ball: 'ground', at: { x: 55, y: 78 }, outcome: 'fielded' };
  const buntMiddle: Spot = { ball: 'bunt', at: { x: 0, y: 30 }, outcome: 'fielded' };

  const rows: [string, string][] = [
    ['Ground ball to an infielder, normal defence', whoHas(groundToShort, {}, 'cover:first')],
    ['First baseman fields it himself', whoHas(groundToFirst, {}, 'cover:first')],
    ['Bunt, normal defence', whoHas(buntMiddle, {}, 'cover:first')],
    ['Bunt, corners in', whoHas(buntMiddle, { posture: 'cornersIn' }, 'cover:first')],
    ['Ground ball, infield in', whoHas(groundToShort, { posture: 'infieldIn' }, 'cover:first')],
  ];

  return [
    '| Situation | Covers first |',
    '| --- | --- |',
    ...rows.map(([what, who]) => `| ${what} | ${who} |`),
  ].join('\n');
}

/** Where the play is a read, and who has to make it. */
function readsSection(): string {
  const cases: { title: string; spot: Spot; over: Partial<Situation> }[] = [
    {
      title: 'Base hit to left, man on first',
      spot: HIT_TO('youth', -31),
      over: { runners: { first: true, second: false, third: false }, outs: 0 },
    },
    {
      title: 'Base hit to left, man on second',
      spot: HIT_TO('youth', -31),
      over: { runners: { first: false, second: true, third: false }, outs: 1 },
    },
    {
      title: 'Ground ball to short, man on third, infield in',
      spot: { ball: 'ground', at: { x: -27, y: 87 }, outcome: 'fielded' },
      over: { runners: { first: false, second: false, third: true }, outs: 0, posture: 'infieldIn' },
    },
    {
      title: 'Ball to the wall, man on second',
      spot: WALL_AT('youth', -17),
      over: { runners: { first: false, second: true, third: false }, outs: 1 },
    },
    {
      title: 'Fly ball caught deep in centre, man on third',
      spot: { ball: 'fly', at: { x: 0, y: 175 }, outcome: 'caught' },
      over: { runners: { first: false, second: false, third: true }, outs: 1 },
    },
  ];

  const out: string[] = [];

  for (const c of cases) {
    const play = run(c.spot, c.over);
    if (!play.branch) {
      out.push(`### ${c.title}`, '', 'No read — the throw is decided.', '');
      continue;
    }

    const main = play.throws.map((t) => BASE_LABEL[t.to]).join(', ') || 'no throw';
    const other = play.branch.throws.map((t) => BASE_LABEL[t.to]).join(', ') || 'no throw';
    const changed = play.assignments.filter((a) => a.alternative);
    const head = `Plays for a throw to **${main}**. ${play.branch.when} — **${other}**.`;

    if (changed.length === 0) {
      out.push(`### ${c.title}`, '', head, '',
        'Nobody picks up a different job — if the read goes the other way the play is simply over.',
        '');
      continue;
    }

    out.push(
      `### ${c.title}`,
      '',
      head,
      '',
      '| Fielder | Plays for | Reads it the other way |',
      '| --- | --- | --- |',
      ...changed.map(
        (a) => `| ${a.position} | ${roleKey(a.role)} | ${roleKey(a.alternative!.role)} |`,
      ),
      '',
    );
  }

  return out.join('\n');
}

/** Rundown assignments, per pair of bases. */
function rundownSection(): string {
  const cases: { over: Partial<Situation> }[] = [
    { over: {} },
    { over: { runners: { first: true, second: false, third: false }, outs: 0 } },
    { over: { runners: { first: false, second: true, third: false }, outs: 1 } },
  ];

  const rows: string[] = [];

  for (const c of cases) {
    const play = run(HIT_TO('youth', -31), c.over);
    const r = play.rundown;
    if (!r) continue;

    const who = (test: (a: Assignment) => boolean) =>
      r.assignments.filter(test).map((a) => a.position).join(', ') || '—';

    const chaser = who((a) => a.role.kind === 'chase');
    const receiver = who((a) => a.role.kind === 'cover' && a.role.base === r.behind);
    const backBehind = who(
      (a) => a.role.kind === 'backupBase' && a.role.base === r.behind,
    );
    const backAhead = who((a) => a.role.kind === 'backupBase' && a.role.base === r.ahead);
    const rotate = r.afterThrow
      .filter((a) => a.role.kind === 'rotate')
      .map((a) => `${a.position} → behind ${r.behind}`)
      .join(', ');

    rows.push(
      `| ${BASE_LABEL[r.behind]} and ${BASE_LABEL[r.ahead]} | ${chaser} | ${receiver} | ${backBehind} | ${backAhead} | ${rotate} |`,
    );
  }

  return [
    'He is always driven back toward the base he came from, so that beating the',
    'tag gains him nothing. One throw is the target; the man who makes it is out',
    'of the play until he gets behind the man he threw to.',
    '',
    '| Between | Has the ball | Takes the throw | Behind the back bag | Behind the front bag | After the throw |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

/** Pickoff plays, and who is where before and after the throw. */
function pickoffSection(): string {
  const situation: Situation = {
    ...DEFAULT_SITUATION,
    runners: { first: true, second: true, third: true },
    outs: 0,
  };
  const cfg = FIELD_CONFIGS.youth;

  const rows = (Object.keys(PICKOFFS) as PickoffId[]).map((id) => {
    const play = buildPickoff(situation, cfg, id);
    const backup =
      play.afterThrow.find((a) => a.role.kind === 'backupBase')?.position ?? '—';
    const decoy = play.assignments.find((a) => a.ruleId === 'pickoff.decoy')?.position ?? '—';
    const early =
      play.assignments.find((a) => a.position === play.spec.cover)!.role.kind === 'cover'
        ? 'yes'
        : 'no';
    return `| ${play.spec.name} | ${play.spec.from} | ${play.spec.cover} | ${backup} | ${decoy} | ${early} |`;
  });

  return [
    'Two things are the same on every one of these. Nobody stands on the bag',
    'before the throw is made, because that is what tells the runner it is',
    'coming; and every throw is backed up, because one that gets away hands over',
    'the base you were trying to take.',
    '',
    '| Play | Throws it | Covers | Backs up | Decoy | On the bag early |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

/** First-and-third calls, and who does what on each. */
function firstThirdSection(): string {
  const situation: Situation = {
    ...DEFAULT_SITUATION,
    runners: { first: true, second: false, third: true },
    outs: 1,
  };
  const cfg = FIELD_CONFIGS.youth;

  const rows = FIRST_THIRD_CALLS.map((call) => {
    const play = buildFirstAndThird(situation, cfg, call);
    const find = (test: (a: Assignment) => boolean) =>
      play.assignments.filter(test).map((a) => a.position).join(', ') || '—';

    const cut = play.assignments.find((a) => a.alternative);
    return `| ${CALL_NAMES[call]} | ${find((a) => a.role.kind === 'throws')} | ${find(
      (a) => a.role.kind === 'cover' && a.role.base === 'second',
    )} | ${cut ? cut.position : '—'} | ${find((a) => a.role.kind === 'backupBase')} |`;
  });

  return [
    'Runners on first and third, one out, right-handed hitter, youth field.',
    'The call is an input, not a recommendation — which one you run depends on',
    'the score, the inning and who is running, none of which this models.',
    '',
    '| Call | Throws it | Covers second | Cuts it | Backs up |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function backupTable() {
  return [
    '| Base | Order of preference |',
    '| --- | --- |',
    ...Object.entries(BACKUP_ORDER).map(
      ([base, order]) => `| ${BASE_LABEL[base]} | ${order.join(', ')} |`,
    ),
  ].join('\n');
}

// --- the document --------------------------------------------------------

const HEADER = `# Playbook

_Generated by \`src/engine/playbook.ts\`. Do not edit by hand — change the rules
and run \`npx vitest -u\`._

This is the review document. Everything below is produced by running the engine,
so it is what the app actually does, not a description of what it is meant to
do. Every claim carries a rule id; if you disagree with one, quote the id.

## Where to push back first

These are the calls that are genuinely arguable — the ones where coaching
systems differ, or where a simplification was made deliberately. If a review
only gets through one section, make it this one.

1. **Youth uses the first baseman to cut every throw home** (\`cut.home\`).
   Adult splits it: third baseman on throws from left, first baseman otherwise.
   Is one cut man for a youth team the right simplification, or does it teach a
   habit that has to be unlearned?
2. **The centre fielder owns both gaps** (\`primary.gap\`). No shared
   responsibility, no "corner outfielder takes it if he is closer".
3. **The 5-6 hole belongs to the shortstop** (\`primary.infield\`), not the
   third baseman ranging left.
4. **A drawn-in infield does not pull the first baseman off the bag**
   (\`cover.first\`) — only bunt defence does (\`cover.first.second\`).
5. **On a base hit with a man on second or third, the throw goes home**
   (\`throws\`), even with two out and even when the run is conceded in practice.
6. **The force at third is only taken when the third baseman is within 25 feet
   of the bag** — otherwise the play goes to second (\`throws\`).
7. **A ball to the wall with anybody on relays home**, never to third.
8. **On a base hit to the outfield, nobody covers first.** The batter-runner is
   uncontested and the first baseman is either cutting or idle.
9. **The outfielder always calls off the infielder in shallow territory**
   (\`primary.shallow.air\`), at every depth in that band.
10. **A ball on the ground within 16 feet of the mound is the pitcher's**
    (\`primary.comebacker\`), whatever sector it is in.
11. **On a straight steal the shortstop covers second against a right-handed
    hitter, the second baseman against a left-hander** (\`ft.cover.second\`).
    In a real game this is a signal between the two of them, and plenty of
    programmes call it the other way round. This is the single claim here I am
    least confident in.
12. **The five first-and-third calls** (\`ft.*\`) are common ones, but this is
    the most system-dependent area in the game — a programme running different
    names and different responsibilities is not wrong. Check the whole section.
13. **The two pickoffs at second differ only in which middle infielder goes**
    (\`pickoff.cover.late\`) — shortstop for the daylight play, second baseman
    for a timing play. Whether those are the right names for those two, and
    whether the man who is not covering should be faking a break at all
    (\`pickoff.decoy\`), is worth a look.
14. **In a rundown the ball starts with whoever took the throw** — he is the
    one who runs the man back, and after his throw he goes to the back of the
    line at the bag he threw to (\`rundown.rotate\`). One throw is the target.
15. **A read has exactly two lines** — the runner goes, or he holds. There is no
    third option, and the defence is always shown playing for the runner going.
    See Reads below.

## What is not modelled

The batter-runner taking an extra base while the throw is elsewhere. A rundown
between home and first is not offered either — it needs a dropped third strike
or a misplayed bunt, not a batted ball being fielded.
`;

export function buildPlaybook(): string {
  const doc: string[] = [HEADER];

  doc.push(
    '## Youth and Adult',
    '',
    'Two places where the level is more than a change of dimensions.',
    '',
    cutTable(),
    '',
    '## Where the throw goes',
    '',
    'Ground ball to the shortstop at normal depth, fielded cleanly, youth field.',
    '',
    throwTable(
      { ball: 'ground', at: { x: -27, y: 87 }, outcome: 'fielded' },
      [
        { label: 'Normal', posture: 'normal' },
        { label: 'Infield in', posture: 'infieldIn' },
      ],
    ),
    '',
    'Base hit dropping into left field, youth field.',
    '',
    throwTable(HIT_TO('youth', -31), [{ label: 'Throw', posture: 'normal' }]),
    '',
    'Fly ball caught in centre field, youth field. A throw here means somebody tagged.',
    '',
    throwTable(
      { ball: 'fly', at: { x: 0, y: 170 }, outcome: 'caught' },
      [{ label: 'Throw', posture: 'normal' }],
    ),
    '',
    '## Reads',
    '',
    'Some throws are not decided at contact. These plays resolve twice — the',
    'line the defence plays for, and the line it plays for if the runner holds —',
    'and any fielder whose job differs between the two has to read the throw.',
    '',
    readsSection(),
    '## Pickoffs',
    '',
    pickoffSection(),
    '',
    '## First and third',
    '',
    firstThirdSection(),
    '',
    '## Rundowns',
    '',
    rundownSection(),
    '',
    '## Who covers first',
    '',
    coverFirstTable(),
    '',
    '## Backups',
    '',
    'Tried in this order; the first man free takes it. A second backup is added',
    'only if somebody is still free and is not on the wrong side of the throw.',
    '',
    backupTable(),
    '',
  );

  for (const level of ['youth', 'adult'] as Level[]) {
    const cfg = FIELD_CONFIGS[level];
    doc.push(
      `## Who owns the ball — ${level === 'youth' ? 'Youth' : 'Adult'}`,
      '',
      `${cfg.baseDistance}' bases, ${cfg.moundDistance}' mound, fences ${cfg.fence.line}/${cfg.fence.center}/${cfg.fence.line}.`,
      '',
      'A `!` means the sample point did not land in the band it was aimed at,',
      'which would mean the band edges have drifted.',
      '',
      '### Infield',
      '',
      ownershipTable(level, ['bunt', 'in', 'infield'], INFIELD_SECTORS),
      '',
      '### Outfield',
      '',
      ownershipTable(level, ['shallow', 'medium', 'deep', 'wall'], OUTFIELD_SECTORS),
      '',
    );
  }

  return doc.join('\n');
}
